import Head from 'next/head';
import Image from 'next/image';
import styles from '../../styles/Home.module.css'
import { createClient } from 'contentful';

export async function getStaticProps() {
  const client = createClient({
    space: process.env.CONTENTFUL_SPACE_ID, // ID of a Compose-compatible space to be used \
    accessToken: process.env.CONTENTFUL_ACCESS_TOKEN, // delivery API key for the space \
  });

  // const semPage = await client.getEntries({content_type: "semPage"});

  // let {fields: pageField} = semPage.items[0];

  return {
    props: {
      // fields: pageField
    }
  }
}

export default function Home({fields}) {
  // console.log("fields", fields);
  // let {title, heroBannerImage: {fields: {file: {url, details:{image: {height, width}}}}}} = fields;

  return (
    <div className={styles.container}>
      <Head>
        <title>Hi this is dummy page</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {/* <h1>{title}</h1>
        <Image 
          src={`https:${url}`}
          width={width}
          height={height}
        ></Image> */}
        </div>
    </div>
  )
}
